# Generated by Django 5.2.1 on 2025-07-05 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0002_remove_prato_nome_chef'),
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='foto_prato',
            field=models.ImageField(blank=True, upload_to='pratos/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='prato',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='funcionario.funcionario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prato',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
